BYU-CS-Discord/CSBot

README.md
package.json
src/commands/__snapshots__/help.test.ts.snap
src/commands/help.test.ts
src/commands/help.ts

At its very basic, `/help` lists the commands available to the user. This is at least a start.
This command will automatically include new commands as they're added in `src/commands/index.ts`.
Closes #8

Basic `/help` functionality

---

src/@types/CommandContext.d.ts
src/commandContext/followUp.test.ts
src/commandContext/followUp.ts
src/commandContext/prepareForLongRunningTasks.test.ts
src/commandContext/prepareForLongRunningTasks.ts
src/commandContext/reply.test.ts
src/commandContext/reply.ts
src/commandContext/replyPrivately.test.ts
src/commandContext/replyPrivately.ts
src/commandContext/sendTyping.test.ts
src/commandContext/sendTyping.ts
src/commands/xkcd.ts
src/handleInteraction.test.ts
src/handleInteraction.ts
src/helpers/actions/deployCommands.test.ts
src/helpers/actions/deployCommands.ts
src/helpers/actions/messages/replyToMessage.test.ts
src/helpers/actions/messages/replyToMessage.ts
src/helpers/actions/revokeCommands.test.ts
src/helpers/actions/revokeCommands.ts
src/helpers/actions/verifyCommandDeployments.test.ts
src/helpers/actions/verifyCommandDeployments.ts
src/logger.ts
src/main.test.ts
src/main.ts

The logger was already partially abstracted before, but it required passing logger around through parameters in methods. This was causing problems for event handler abstraction.
Now the logger is in a separate file called `logger.ts` that contains a method that returns the logger to use (the console, for now). We use a method instead of a constant to make mocking easier for tests.
All files that used the logger before now pull the logger from `logger.ts` instead of passing through parameters. I also updated tests to reflect this fact by mocking `logger.ts`.

Logger abstraction

---

.prettierrc
.vscode/settings.json
README.md

(Will resolve Issue #34)
On Windows, Prettier was throwing errors because it expected Unix-style line endings. Now VS Code and Prettier should accept the default line endings of whatever operating system the project is on.
On Windows, `npm` scripts would fail because the Windows terminal did not accept Linux commands or file directories. Now VS Code should default to using Git Bash for the terminal, and a note was added to the README for Windows users to set `npm`'s default script shell to Git Bash.
And on a side note, I also added a setting to tell VS Code to auto-format files on save.

Compatibility for Windows Dev Environments

---

.npmrc
src/@types/EventHandler.d.ts
src/events/error.ts
src/events/index.test.ts
src/events/index.ts
src/events/interactionCreate.ts
src/events/ready.ts
src/helpers/actions/messages/replyToMessage.test.ts
src/helpers/onEvent.test.ts
src/helpers/onEvent.ts

Based on a discussion in https://github.com/BYU-CS-Discord/CSBot/pull/38#discussion_r985288404
The goal here is to remove the need for us to look up the params of each event when writing new event handlers, or maintaining existing ones. This makes the syntax of registering handlers slightly more complicated, but since that code is infrequently modified, I think a few words of boilerplate aren't too bad.

Made `EventHandler` generic over its `name` property

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/constants/reactionDuplication.ts
src/events/index.ts
src/events/messageReactionAdd.test.ts
src/events/messageReactionAdd.ts
src/helpers/actions/messages/replyToMessage.test.ts

New stuff:
- The bot now duplicates some initial message reactions.
- :star: is ignored
- 1 in 5 chance for :same: and :no_u:
- 1 in 100 for every other emoji
- Emoji names are case-normalized (e.g. any capitalization of :same: will do)
I anticipate we can make these odds configurable once we have the database fleshed out. We'd need at least:
- Some place to store the default reaction chance
- Some place to store the names and off-chances of each special emoji
- Some way to tie those emoji to the eventual X-board (to prevent the bot from affecting those stats) without excess database I/O
Closes #24

First go at reaction duplication

---

.github/workflows/test.yml
dockerfile

Currently, our Docker container automatically uses the latest version of Node, which just updated to v19. This is probably unstable. It might be best to hard-lock our dev environment to v16 until we know if our dependencies support v18 LTS.

Hotfix - Node v16

---

.eslintrc
src/@types/CommandContext.d.ts
src/commands/profile.test.ts
src/commands/profile.ts
src/helpers/DiscordErrorCode.ts

Some new safety guards:
- When getting another user's profile, we ping that user. Run the command in a locked channel to get profile stuff secretly. (Or just use Inspect Element.)
- Can't get a user's profile when that user isn't a member of the server.
- Can only get your own profile or that of the bot when in DMs.
- The output is organized into an embed, with clear room for future enhancement.

Nerf `/profile`

---

src/events/interactionCreate.ts

Fixes `/xkcd` options not working right at all not at all no.

fix: Include options in call handlers

---

.eslintrc
.github/workflows/create-release.yml
.github/workflows/versions-match.yml
.prettierignore
CHANGELOG.md
package-lock.json
package.json
scripts/assertTsNode.ts
scripts/release.ts
tsconfig.test.json

1. Update CHANGELOG.md
2. Run `npm run release`
3. ???
4. Profit
The script automatically adjusts the links at the bottom to match. Simply follow the regular format and all will be well.
Also added new CI/CD steps to automatically cut a new tag and GitHub Release page as new versions roll in.

Auto-release

---

.github/workflows/test.yml

It seems that `ArtiomTr/jest-coverage-report-action` doesn't support external PRs. I'm not certain that [the official workaround](https://github.com/ArtiomTr/jest-coverage-report-action#forks-with-no-write-permission) works for our purposes. I figure we should disable the coverage report for now, pending more research, since external contributions are ramping up.
Let's keep up coverage, though! We'll get a proper coverage report as soon as we figure out how to do that :P

Disable coverage report

---

package-lock.json

npm reported a vulnerability in the `undici` dependency (of some other dependency). This updates the `package-lock.json` to use the patched version.

Updated version of vulnerable undici dependency

---

jest.config.json
package-lock.json

Based on #75, except we also fix our Jest config.
Thanks @josephgeis for the help on the dependency update, and credit goes to https://github.com/nodejs/undici/issues/1878#issuecomment-1421484960 for pointing out the solution for Jest.

Updated version of vulnerable undici dependency (pt. 2)

---

.vscode/settings.json
CHANGELOG.md
package-lock.json
package.json
src/commands/findRoom.ts
src/commands/xkcd.test.ts
src/commands/xkcd.ts
src/helpers/HttpStatusCode.ts
src/helpers/NetworkError.ts
src/helpers/fetch.test.ts
src/helpers/fetch.ts

Since [Node 18 includes the `fetch` API](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) (and that support is [no longer experimental](https://stackoverflow.com/a/75221620)), we can drop a dependency when we upgrade. Since Node's `fetch` implementation is `undici`, I think it would be prudent to use that one for now. Once we're on Node 18, we can remove `undici` (or [move it into devDependencies for type information](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924#issuecomment-1504635244)) for a smaller bundle.
Axios is a fine package, as far as I can tell, and very popular, even since Node 18. The `fetch` API is also popular (see [`node-fetch`](https://github.com/node-fetch/node-fetch) and the browser-native …

Prefer Undici over Axios

---

CHANGELOG.md
package-lock.json
package.json

- Resolved all npm vulnerabilities using `npm audit fix`
- Fixed axios vulnerability with override
`pm2` relies on an outdated version of `axios` with a vulnerability. It appears the owner of `pm2` has gone inactive and the project is no longer maintained. An override is the [suggested solution](https://github.com/keymetrics/pm2-io-js-api/pull/77#issuecomment-1871651146) from the community.
In the long term, it may be worthwhile to replace `pm2`.

Resolve all npm vulnerabilities

---

CHANGELOG.md
README.md
src/commands/contextMenu/fxtwitter.test.ts
src/commands/contextMenu/fxtwitter.ts
src/helpers/positionsOfUriInText.test.ts
src/helpers/positionsOfUriInText.ts

- Support for converting `x.com` links to `fixupx.com` (see the updated [FxTwitter](https://github.com/FixTweet/FxTwitter))
- Missing code coverage in `positionsOfUriInText` by making it return an empty array instead of null when there are no matches
- Missing code coverage in `fxtwitter.ts` by moving URL-parsing error checking to `positionsOfUriInText` and checking what happens if the uri regex matches an invalid URI

Add support for x.com links in fxtwitter

---

.github/workflows/codeql-analysis.yml
.github/workflows/create-release.yml
.github/workflows/validate.yml
.github/workflows/versions-match.yml
CHANGELOG.md

- Renamed Test workflow to Validate to better represent all the steps besides testing
- All workflows to use `checkout@v4` instead of `v3`
- Validate workflow to use `setup-node` instead of Docker container
- All `setup-node` steps to use `.nvmrc` to define node version
- Validate workflow to run on push to main as well as pull request
- "own all files" step from Validate workflow

Revamp GitHub workflows

---

package-lock.json
package.json
src/commands/__snapshots__/toTheGallows.test.ts.snap
src/evilHangman/__snapshots__/evilHangmanAsciiArt.test.ts.snap

- All `vitest` dependencies to be up-to-date with post-1.0.0 release
- `vite` vulnerability by updating to 5.0.12
- `uuid` deprecation with 9.0.0 override

Resolve vite and uuid vulnerabilities

---

eslint.config.js
src/commands/stats.ts
src/commands/talk.ts
src/events/interactionCreate.ts
src/helpers/NetworkError.ts

This PR is mostly cleanup from the migration to ESM, pulling changes from #87 that I missed.
- Renamed typescript plugins in eslint config to match others
- Caught more instances of explicit type imports
- `__dirname not defined` bug when privatizing error messages in `interactionCreate.ts`

Fix dirname not defined bug

---

CHANGELOG.md
Dockerfile
README.md
eslint.config.js
package-lock.json
package.json
src/commands/contextMenu/talk.test.ts
src/commands/contextMenu/talk.ts
src/commands/talk.test.ts
src/commands/talk.ts

The old `dectalk` package was a little sketchy - it created a child process to run an unprotected executable on the local machine, and it required special OS dependencies on Linux. And it didn't work on Mac.
This new package simply calls a web API, so the dectalk executable does not need to be run locally anymore. This should be much safer.

Use new dectalk-tts package

---

.github/workflows/codeql-analysis.yml
.github/workflows/validate.yml
.github/workflows/versions-match.yml

`setup-node@v3` used Node 16 for actions, which has been [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) and support will be ended soon. Right now, we get a warning message whenever we run a workflow with `setup-node@v3`.
The same problem applies to `codeql-action@v2`. Support for v2 will end December 2024 (see [here](https://github.com/github/codeql-action?tab=readme-ov-file#supported-versions-of-the-codeql-action)), so we should update to v3.

Update GitHub actions to latest versions

---

LICENSE
README.md
package-lock.json
package.json

[Apparently](https://opensource.stackexchange.com/a/12073), the public domain dedication in Unlicense makes our code unusable in jurisdictions where public domain is not a recognized legal concept.
Per [our original discussion](https://discord.com/channels/1024162246491914240/1024162247041359895/1024179046306811904) on this, we want a license that gives "zero conditions, full permissions". In the spirit of that goal, I recommend we use 0BSD instead of Unlicense.

Prefer 0BSD over Unlicense

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Link the bot-specific server invite, instead of the one for the main server.

docs: Use more specific server invite

---

CHANGELOG.md
eslint.config.js
package-lock.json
package.json

https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/
-----
- Replaced both `@typescript-eslint/...` v6 packages with `typescript-eslint` v7 package
- Extend the new flat configs
- Turned off a new strict type-checking rule that was giving us lots of errors (fix this later)

Upgrade to typescript-eslint v7

---

.github/workflows/mirror.yml
README.md

In the interest of not "keeping all our eggs in one basket", and in case GitHub goes down again, it seems reasonable to maintain a code mirror on another reliable forge, such as [Codeberg](https://codeberg.org).
Since Codeberg will not do automatic code pulls, we must push code there ourselves. I've set up [a dedicated account](https://codeberg.org/byu-cs-discord-mirror-bot) for this purpose on [our mirror org over there](https://codeberg.org/BYU-CS-Discord), and this PR facilitates the push each time new code hits our `main` branch.

feat: Add CI workflow to push code to Codeberg

---

CHANGELOG.md
src/commands/findRoom.ts

Fix `/findroom between` using buildings as `end_time` choices

---

.github/workflows/deploy-docker.yml
CHANGELOG.md
package-lock.json
package.json

Added another Docker tag config to target specific versions. Not sure why v0.13.0 failed to deploy, so this new tag run might give me more info

chore: Also tag sha hash in Docker

---

.github/workflows/create-release.yml
CHANGELOG.md
package-lock.json
package.json

Figured out why our Docker deploy was failing to push semver tags. Turns out, it's because we were using `GITHUB_TOKEN` to cut releases. [GitHub won't let `GITHUB_TOKEN` trigger another workflow.](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow) 😔
I set up my own personal token for now. Eventually we may want to find a different way to run the deployments.

Trigger tag push event from the release workflow

---

.github/dependabot.yml
CHANGELOG.md

Made some changes to reflect what I've done in personal projects.
- Added updates for GitHub Actions
- Set versioning strategy to "increase" (this fixes situations where dependabot only updates `package-lock.json` without bumping the version in `package.json`)
- Fixed the last update's release date
- Fixed the missing "Unreleased" section

Add GitHub Actions updates for Dependabot

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/events/ready.ts
src/workers/uptime.ts

Would be nice to have some kind of status page. I have an Uptime Kuma instance at https://status.byucs.genericlookinglink.com that so far only shows the RoomFinder back-end. We can additionally configure a monitor to receive GET requests from CSBot every so often to indicate up-ness.
This PR adds configuration options for that URL and the ping interval, and runs a loop on a worker thread to ping the back-end, with reasonable logging.
I also cut a new version, since I kinda want this out as soon as we can :sweat_smile:

GET a configured URL every so often
